### ISSUE TITLE
rewrite in node.js

### ISSUE THREAD

**Issue by wirepair** [bnagy/cgasm#1]
i feel this has something left to be desired... something closer to the metal.
Can you rewrite this in node.js?

**Comment by dullgiulio** [comment]
I wish this tool had PDF output! Is it going to be added?

**Comment by bnagy** [comment]
https://github.com/bnagy/cgasm#contributing

**Comment by Rami114** [comment]
OP request implemented in https://github.com/Rami114/nodeasm/
