### ISSUE TITLE
Incorrect handling of Jcc (and many other) aliases

### ISSUE THREAD

**Issue by bnagy** [bnagy/cgasm#2]
https://twitter.com/Schtrudel/status/623065684063440896

**Comment by bnagy** [comment]
Hopefully fixed in 09228c0dd5a4a15780e5abb533ca31762139663a

**Comment by Schtrudel** [comment]
It's fine now. All the Jxx seems to work. 
Jcc is not an alias, but the generic, so the error report example still gives the same output. But the pointers are working now, and that's what important.

> JNGE -> Jcc - Jump if Condition Is Met
> JNL -> Jcc - Jump if Condition Is Met
> etc...

Still, the truncated summary is not of any help for these commands, and for example, in these cases, an output like this would have been more helpful (the info is part of the full doc "-v"):

> JNL rel8:  Jump short if not less (SF=OF).

**Comment by bnagy** [comment]
... this is hard.
