### ISSUE TITLE
Overloaded MOV instruction?

### ISSUE THREAD

**Issue by Schtrudel** [bnagy/cgasm#9]
MOV returns the "MOV - Move to/from Debug Registers" (0F 21/0F 23)
but how to access the "straightforward" MOV (88/89/8A/...)  ? 

Even   _cgasm -f mov*|grep "MOV "_     doesn't return it.

**Comment by bnagy** [comment]
It's a problem with the database. There are three SQL entries that get added as MOV and the last one has won. This is difficult to handle gracefully with a commandline tool. Mostly I have just been making an executive decision when similar issues have come up. If you can think of a nice way of handling the disambiguation then let me know.

I'll leave this open - it should return 'normal' MOV by default. Will fix.

**Comment by bnagy** [comment]
Try it now

**Comment by Schtrudel** [comment]
So you invented new mnemo. But since you looked for a way of disambiguation, what about something like that with the optional other parameter?

```
> cgasm mov
[ Disambiguation:
[ MOV (1) [default]- Move
[ MOV (2) - Move to/from Control Registers
[ MOV (3) - Move to/from Debug Registers 

MOV - Move                                                                                   

Description:                                                                                 
Copies the second operand (source operand) to the first operand (destination                 
operand). The source operand can be an immediate value, general-purpose register,            
segment register, or memory location; the destination register can be a general-purpose      
register, segment register, or memory location. Both operands must be the same               
size, which can be a byte, a word, a doubleword, or a quadword.               

> cgasm mov 2
MOV - Move to/from Control Registers

Description:
Moves the contents of a control register (CR0, CR2, CR3, CR4, or CR8) to a general-purpose
register or the contents of a general purpose register to a control register.
The operand size for these instructions is always 32 bits in non-64-bit modes,
regardless of the operand-size attribute. (See “Control Registers” in Chapter
2 of the Intel®64 and IA-32 Architectures Software Developer''s Manual, Volume
3A, for a detailed description of the flags and fields in the control registers.)
This instruction can be executed only when the current privilege level is 0.

> cgasm -f mov
MOV (1) - Move               
MOV (2) - Move to/from Control Registers
MOV (3) - Move to/from Debug Registers 
```

**Comment by bnagy** [comment]
It's a good idea. Do you happen to know if this comes up for anything _but_ MOV? If so, would you mind opening your idea as a new issue so I can label it enhancement and do it when I have time? If not, I think this is probably sufficient (this is a pretty quick and dirty tool).

Thanks a lot for the report!

**Comment by Schtrudel** [comment]
I didn't find another case like that. So it's probably not worth the effort for one case to make it generic.
Thanks!
